<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Kollus Play Video By PHP</title>

    <link rel="shortcut icon" href="/img/favicon.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://highlightjs.org/static/demo/styles/darkula.css">
    <link rel="stylesheet" href="/css/default.css">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://highlightjs.org/static/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
<nav class="navbar navbar-default  navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Kollus Play Video By PHP</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="https://github.com/kollus-service/kollus-play-video-php"><i class="fa fa-github"></i> Github</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    <div class="page-header">
        <h1>Play video using Kollus Webtoken</h1>
    </div>

    <div class="flashes">
        <?php if (!$existsConfig): ?>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>Config file is not found.
            </div>
        <?php endif; ?>
    </div>

    <div class="well">
        <form action="/" id="login-form" method="post">
            <fieldset <?php if (!$existsConfig) { echo 'disabled'; }; ?>>
                <?php if ($existsConfig): ?>
                    <div class="form-group">
                        <label>Service account key</label>
                        <p class="form-control-static"><?php echo $kollus['service_account']['key']; ?></p>
                    </div>

                    <div class="form-group">
                        <label>Kollus domain</label>
                        <p class="form-control-static"><?php echo $kollus['domain']; ?></p>
                    </div>

                    <div class="form-group">
                        <label for="client-user-id">Client User ID</label>
                        <input type="text" class="form-control" id="client-user-id" name="client_user_id" placeholder="Please type client user id" required>
                    </div>

                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-sign-in"></i> Login
                    </button>
                <?php endif; ?>
            </fieldset>
        </form>
    </div>

    <hr />

    <footer class="footer">
        <p>2017 &copy; Catenoid, inc.</p>
    </footer>

</div>
<!--[if lt IE 10]>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<![endif]-->
<!--[if (gte IE 10)|!(IE)]><!-->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!--<![endif]-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js" integrity="sha256-1hjUhpc44NwiNg8OwMu2QzJXhD8kcj+sJA3aCQZoUjg=" crossorigin="anonymous"></script>
<script src="/js/default.js"></script>
</body>
</html>
